# Antigen
source ~/.antigen_git/antigen.zsh

## Auto Update
antigen bundle unixorn/autoupdate-antigen.zshplugin

## Lib files
antigen bundle robbyrussell/oh-my-zsh lib/

## Basic Bundles
antigen bundle djui/alias-tips
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle git
antigen bundle common-aliases
antigen bundle github
antigen bundle caarlos0/zsh-open-pr
antigen bundle adb

## Ruby Bundles
antigen bundle ruby
antigen bundle gem
antigen bundle rbenv
antigen bundle bundler

## OS specific plugins
if [[ $CURRENT_OS == 'OS X' ]]; then
    antigen bundle brew
    antigen bundle brew-cask
    antigen bundle osx
elif [[ $CURRENT_OS == 'Linux' ]]; then
    # None so far...

    if [[ $DISTRO == 'CentOS' ]]; then
        # None so far..
    fi
fi

## Antigen apply
antigen apply

# Basic settings
export PATH="/usr/local/sbin:/usr/local/bin:/bin:/usr/sbin:/sbin:/usr/bin:$ADB_HOME:$PATH"
export EDITOR='vi'
export JAVA_HOME='/usr'

# Aliases
alias apk_install="$ADB_HOME/adb install -r $@"

# Shortcuts
export DOWNLOAD_HOME="$HOME/Downloads"
export APK_HOME="$DOWNLOAD_HOME/APKs"

# TEM
source ~/code/git/tem/em.sh

# RBEnv
eval "$(rbenv init -)"

# Use EMacs mode
bindkey -e

# online help
#unalias run-help
autoload run-help
HELPDIR=/usr/local/share/zsh/help 
