# Antibody
source <(antibody init)

# Prompt
antibody bundle nojhan/liquidprompt

## Lib files
#antibody bundle robbyrussell/oh-my-zsh lib/

## Basic Bundles
antibody bundle djui/alias-tips
antibody bundle zsh-users/zsh-syntax-highlighting
antibody bundle paraqles/zsh-plugin-git
#antibody bundle common-aliases
#antibody bundle github
antibody bundle caarlos0/zsh-open-pr
#antibody bundle adb
antibody bundle rupa/z
antibody bundle supercrabtree/k
antibody bundle s7anley/zsh-geeknote
antibody bundle zsh-users/zsh-autosuggestions
#antibody bundle history
#antibody bundle vi-mode
antibody bundle chrissicool/zsh-256color
antibody bundle horosgrisa/autoenv
antibody bundle https://github.com/zsh-users/zsh-history-substring-search
antibody bundle zsh-users/zsh-completions
#antibody bundle tmux
#antibody bundle tmuxinator

## Ruby Bundles
antibody bundle paraqles/zsh-plugin-ruby
#antibody bundle rbenv

antibody bundle pelletiermaxime/test-kitchen-zsh-plugin

## OS specific plugins
if [[ $CURRENT_OS == 'OS X' ]]; then
    antibody bundle paraqles/zsh-plugin-mac
    #antibody bundle brew
    #antibody bundle brew-cask
elif [[ $CURRENT_OS == 'Linux' ]]; then
    # None so far...

    if [[ $DISTRO == 'CentOS' ]]; then
        # None so far..
    fi
fi

## Antigen apply
#antibody apply

# Basic settings
export PATH="/usr/local/sbin:/usr/local/bin:/bin:/usr/sbin:/sbin:/usr/bin:$ADB_HOME:$PATH"
export EDITOR='vim'
export JAVA_HOME='/usr'

# Aliases
alias apk_install="$ADB_HOME/adb install -r $@"

# Shortcuts
export DOWNLOAD_HOME="$HOME/Downloads"
export APK_HOME="$DOWNLOAD_HOME/APKs"

# online help
autoload run-help
HELPDIR=/usr/local/share/zsh/help

# ATOM
export ATOM_HOME=${0%/*}/../atom

# The Fuck
#alias fuck='$(thefuck $(fc -ln -1))'

# Preserve History
HISTSIZE=5000               #How many lines of history to keep in memory
HISTFILE=~/.zsh_history     #Where to save history to disk
SAVEHIST=5000               #Number of history entries to save to disk
HISTDUP=erase               #Erase duplicates in the history file
setopt    appendhistory     #Append history to the history file (no overwriting)
setopt    sharehistory      #Share history across terminals
setopt    incappendhistory  #Immediately append to the history file, not just when a term is killed

# RbEnv init
#eval "$(rbenv init -)"
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
