# Antigen
source ${0%/*}/../antigen/antigen.zsh

# Prompt
antigen bundle nojhan/liquidprompt

## Lib files
antigen bundle robbyrussell/oh-my-zsh lib/

## Basic Bundles
antigen bundle djui/alias-tips
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle git
antigen bundle common-aliases
antigen bundle github
antigen bundle caarlos0/zsh-open-pr
antigen bundle adb
antigen bundle rupa/z
antigen bundle supercrabtree/k
antigen bundle s7anley/zsh-geeknote
antigen bundle tarruda/zsh-autosuggestions
antigen bundle history
antigen bundle vi-mode
antigen bundle chrissicool/zsh-256color
antigen bundle horosgrisa/autoenv
antigen bundle https://github.com/zsh-users/zsh-history-substring-search
antigen bundle zsh-users/zsh-completions src
antigen bundle tmux
antigen bundle tmuxinator

## Ruby Bundles
antigen bundle ruby
antigen bundle gem
antigen bundle rbenv
antigen bundle bundler

antigen bundle pelletiermaxime/test-kitchen-zsh-plugin

## OS specific plugins
if [[ $CURRENT_OS == 'OS X' ]]; then
    antigen bundle brew
    antigen bundle brew-cask
    antigen bundle osx
elif [[ $CURRENT_OS == 'Linux' ]]; then
    # None so far...

    if [[ $DISTRO == 'CentOS' ]]; then
        # None so far..
    fi
fi

## Antigen apply
antigen apply

# Basic settings
export PATH="/usr/local/sbin:/usr/local/bin:/bin:/usr/sbin:/sbin:/usr/bin:$ADB_HOME:$PATH"
export EDITOR='vim'
export JAVA_HOME='/usr'

# Aliases
alias apk_install="$ADB_HOME/adb install -r $@"

# Shortcuts
export DOWNLOAD_HOME="$HOME/Downloads"
export APK_HOME="$DOWNLOAD_HOME/APKs"

# online help
autoload run-help
HELPDIR=/usr/local/share/zsh/help 

# ATOM
export ATOM_HOME=${0%/*}/../atom

# The Fuck
alias fuck='$(thefuck $(fc -ln -1))'

# RbEnv init
eval "$(rbenv init -)"
